name: Proper use of variables (sercret & envirnoment variables)

on: push

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    name: Staging
    env:
      AWS_REGION: us-east-1
      CONTAINER_NNAME: nice-app-service
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Configure AWS credentails
        uses: aws-actions/configure-aws-credentuals@v4 # any attibute can come with a 'with' attr
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}} #do no put these tokens in env: above - dangerous
          aws-secret-key-id: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
          aws-region: ${{env.AWS_REGION}}
